#!/usr/bin/env bash

cd $CERTS_DIR

FILES=$(ls *.pem)

for FILE in $FILES; do
  size=$(wc -c <"$FILE" )
  if [ $size -gt 100 ]; then
    if [[ $FILE == *"_"* ]]; then
      TYPE=$(echo $FILE | awk 'BEGIN { FS = "_" } ; { print $1 }')
      HOST=$(echo $FILE | sed "s/^${TYPE}_//" | sed "s/\.pem$//" )

      rm /tmp/storefile
      vault read -field=value $VAULT_PATH/$HOST/$TYPE > /tmp/storefile
      different=$( cmp -s /tmp/storefile $FILE || echo 1 )

      if [ -n "$different" ]; then
        echo "Store $FILE to $VAULT_PATH/$HOST/$TYPE"
        cat $FILE | vault write $VAULT_PATH/$HOST/$TYPE value=- ttl=86400
      fi

      rm /tmp/storefile
    fi
  fi
done
