#!/usr/bin/env sh

cd "$CERTS_DIR"

files=$(ls *.pem)

for file in $files; do
  size=$(wc -c <"$file" )

  if [ "$size" -gt 100 ]; then
    if [ -n $( echo "$file" | fgrep '_' ) ]; then
      vault token-renew > /dev/null

      if [ "$?" != "0" ]; then
        echo "Unsuccessfull renew access to vault"
        exit
      fi

      TYPE=$(echo "$file" | awk 'BEGIN { FS = "_" } ; { print $1 }')
      HOST=$(echo "$file" | sed "s/^${TYPE}_//" | sed "s/\.pem$//" )

      stored=""

      while [ -z "$stored" ]; do
        echo "Store $file to $VAULT_PATH/$HOST/$TYPE"

        cat "$file" | vault write "$VAULT_PATH/$HOST/$TYPE" value=- ttl=1d

        if [ "$?" != "0" ]; then
          echo "Unsuccessfull write access to vault"
          exit
        fi

        sleep 2

        rm /tmp/storefile >/dev/null 2>/dev/null
        vault read -field=value "$VAULT_PATH/$HOST/$TYPE" > /tmp/storefile

        if [ "$?" != "0" ]; then
          echo "Unsuccessfull read access to vault"
          exit
        fi

        different=$( cmp -s /tmp/storefile "$file" || echo 1 )

        if [ -n "$different" ]; then
          echo "Different"
        else
          echo "Equal"
          stored="1"
        fi

      done

      echo "Stored $file"
      rm "$file"

      rm /tmp/storefile >/dev/null 2>/dev/null
    fi
  fi
done
